/*
 * ZBounce Email Engine Platform
 * ZBounce Email Engine Platform API Reference
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiCallback;
import org.openapitools.client.ApiClient;
import org.openapitools.client.ApiException;
import org.openapitools.client.ApiResponse;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;
import org.openapitools.client.ProgressRequestBody;
import org.openapitools.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import org.openapitools.client.model.BatchEmail;
import org.openapitools.client.model.BatchResponse;
import org.openapitools.client.model.CreateScheduledMailingReq;
import org.openapitools.client.model.CreateScheduledMailingResp;
import org.openapitools.client.model.CreateTaskRequest;
import org.openapitools.client.model.DeleteScheduledMailingResp;
import org.openapitools.client.model.DomainInfo;
import org.openapitools.client.model.DomainRegisterReq;
import org.openapitools.client.model.EmailReport;
import org.openapitools.client.model.FastVerifyRequest;
import org.openapitools.client.model.GetScheduledMailingResp;
import org.openapitools.client.model.ListScheduledMailingsResp;
import org.openapitools.client.model.PaginatedResults;
import org.openapitools.client.model.TaskResponse;
import org.openapitools.client.model.TaskStatusResponse;
import org.openapitools.client.model.UpdateScheduledMailingReq;
import org.openapitools.client.model.UpdateScheduledMailingResp;
import org.openapitools.client.model.V1DomainsDomainPatch200Response;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class PublicApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public PublicApi() {
        this(Configuration.getDefaultApiClient());
    }

    public PublicApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for v1DomainsDomainPatch
     * @param domain  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Verification result </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Domain not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1DomainsDomainPatchCall(@javax.annotation.Nonnull String domain, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/domains/{domain}"
            .replace("{" + "domain" + "}", localVarApiClient.escapeString(domain.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PATCH", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1DomainsDomainPatchValidateBeforeCall(@javax.annotation.Nonnull String domain, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'domain' is set
        if (domain == null) {
            throw new ApiException("Missing the required parameter 'domain' when calling v1DomainsDomainPatch(Async)");
        }

        return v1DomainsDomainPatchCall(domain, _callback);

    }

    /**
     * Verify DNS TXT records of domain
     * 
     * @param domain  (required)
     * @return V1DomainsDomainPatch200Response
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Verification result </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Domain not found </td><td>  -  </td></tr>
     </table>
     */
    public V1DomainsDomainPatch200Response v1DomainsDomainPatch(@javax.annotation.Nonnull String domain) throws ApiException {
        ApiResponse<V1DomainsDomainPatch200Response> localVarResp = v1DomainsDomainPatchWithHttpInfo(domain);
        return localVarResp.getData();
    }

    /**
     * Verify DNS TXT records of domain
     * 
     * @param domain  (required)
     * @return ApiResponse&lt;V1DomainsDomainPatch200Response&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Verification result </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Domain not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<V1DomainsDomainPatch200Response> v1DomainsDomainPatchWithHttpInfo(@javax.annotation.Nonnull String domain) throws ApiException {
        okhttp3.Call localVarCall = v1DomainsDomainPatchValidateBeforeCall(domain, null);
        Type localVarReturnType = new TypeToken<V1DomainsDomainPatch200Response>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Verify DNS TXT records of domain (asynchronously)
     * 
     * @param domain  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Verification result </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid request </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Domain not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1DomainsDomainPatchAsync(@javax.annotation.Nonnull String domain, final ApiCallback<V1DomainsDomainPatch200Response> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1DomainsDomainPatchValidateBeforeCall(domain, _callback);
        Type localVarReturnType = new TypeToken<V1DomainsDomainPatch200Response>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1DomainsGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of registered domains </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1DomainsGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/domains";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1DomainsGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return v1DomainsGetCall(_callback);

    }

    /**
     * List sender domains
     * 
     * @return List&lt;DomainInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of registered domains </td><td>  -  </td></tr>
     </table>
     */
    public List<DomainInfo> v1DomainsGet() throws ApiException {
        ApiResponse<List<DomainInfo>> localVarResp = v1DomainsGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List sender domains
     * 
     * @return ApiResponse&lt;List&lt;DomainInfo&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of registered domains </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<DomainInfo>> v1DomainsGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = v1DomainsGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<List<DomainInfo>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List sender domains (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of registered domains </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1DomainsGetAsync(final ApiCallback<List<DomainInfo>> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1DomainsGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<List<DomainInfo>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1DomainsPost
     * @param domainRegisterReq  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Registration info with TXT records </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1DomainsPostCall(@javax.annotation.Nonnull DomainRegisterReq domainRegisterReq, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = domainRegisterReq;

        // create path and map variables
        String localVarPath = "/v1/domains";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1DomainsPostValidateBeforeCall(@javax.annotation.Nonnull DomainRegisterReq domainRegisterReq, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'domainRegisterReq' is set
        if (domainRegisterReq == null) {
            throw new ApiException("Missing the required parameter 'domainRegisterReq' when calling v1DomainsPost(Async)");
        }

        return v1DomainsPostCall(domainRegisterReq, _callback);

    }

    /**
     * Register new sender domain
     * 
     * @param domainRegisterReq  (required)
     * @return DomainInfo
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Registration info with TXT records </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public DomainInfo v1DomainsPost(@javax.annotation.Nonnull DomainRegisterReq domainRegisterReq) throws ApiException {
        ApiResponse<DomainInfo> localVarResp = v1DomainsPostWithHttpInfo(domainRegisterReq);
        return localVarResp.getData();
    }

    /**
     * Register new sender domain
     * 
     * @param domainRegisterReq  (required)
     * @return ApiResponse&lt;DomainInfo&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Registration info with TXT records </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DomainInfo> v1DomainsPostWithHttpInfo(@javax.annotation.Nonnull DomainRegisterReq domainRegisterReq) throws ApiException {
        okhttp3.Call localVarCall = v1DomainsPostValidateBeforeCall(domainRegisterReq, null);
        Type localVarReturnType = new TypeToken<DomainInfo>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Register new sender domain (asynchronously)
     * 
     * @param domainRegisterReq  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Registration info with TXT records </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1DomainsPostAsync(@javax.annotation.Nonnull DomainRegisterReq domainRegisterReq, final ApiCallback<DomainInfo> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1DomainsPostValidateBeforeCall(domainRegisterReq, _callback);
        Type localVarReturnType = new TypeToken<DomainInfo>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1FastVerifyPost
     * @param fastVerifyRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid JSON </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Invalid key / exhausted quota </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Server busy </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1FastVerifyPostCall(@javax.annotation.Nonnull FastVerifyRequest fastVerifyRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = fastVerifyRequest;

        // create path and map variables
        String localVarPath = "/v1/fast-verify";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1FastVerifyPostValidateBeforeCall(@javax.annotation.Nonnull FastVerifyRequest fastVerifyRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'fastVerifyRequest' is set
        if (fastVerifyRequest == null) {
            throw new ApiException("Missing the required parameter 'fastVerifyRequest' when calling v1FastVerifyPost(Async)");
        }

        return v1FastVerifyPostCall(fastVerifyRequest, _callback);

    }

    /**
     * Fast single-address verification
     * 
     * @param fastVerifyRequest  (required)
     * @return EmailReport
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid JSON </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Invalid key / exhausted quota </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Server busy </td><td>  -  </td></tr>
     </table>
     */
    public EmailReport v1FastVerifyPost(@javax.annotation.Nonnull FastVerifyRequest fastVerifyRequest) throws ApiException {
        ApiResponse<EmailReport> localVarResp = v1FastVerifyPostWithHttpInfo(fastVerifyRequest);
        return localVarResp.getData();
    }

    /**
     * Fast single-address verification
     * 
     * @param fastVerifyRequest  (required)
     * @return ApiResponse&lt;EmailReport&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid JSON </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Invalid key / exhausted quota </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Server busy </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<EmailReport> v1FastVerifyPostWithHttpInfo(@javax.annotation.Nonnull FastVerifyRequest fastVerifyRequest) throws ApiException {
        okhttp3.Call localVarCall = v1FastVerifyPostValidateBeforeCall(fastVerifyRequest, null);
        Type localVarReturnType = new TypeToken<EmailReport>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Fast single-address verification (asynchronously)
     * 
     * @param fastVerifyRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid JSON </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Invalid key / exhausted quota </td><td>  -  </td></tr>
        <tr><td> 429 </td><td> Server busy </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1FastVerifyPostAsync(@javax.annotation.Nonnull FastVerifyRequest fastVerifyRequest, final ApiCallback<EmailReport> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1FastVerifyPostValidateBeforeCall(fastVerifyRequest, _callback);
        Type localVarReturnType = new TypeToken<EmailReport>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ScheduledMailingsGet
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of scheduled mailings </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsGetCall(final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/scheduled-mailings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ScheduledMailingsGetValidateBeforeCall(final ApiCallback _callback) throws ApiException {
        return v1ScheduledMailingsGetCall(_callback);

    }

    /**
     * List scheduled mailings
     * 
     * @return ListScheduledMailingsResp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of scheduled mailings </td><td>  -  </td></tr>
     </table>
     */
    public ListScheduledMailingsResp v1ScheduledMailingsGet() throws ApiException {
        ApiResponse<ListScheduledMailingsResp> localVarResp = v1ScheduledMailingsGetWithHttpInfo();
        return localVarResp.getData();
    }

    /**
     * List scheduled mailings
     * 
     * @return ApiResponse&lt;ListScheduledMailingsResp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of scheduled mailings </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ListScheduledMailingsResp> v1ScheduledMailingsGetWithHttpInfo() throws ApiException {
        okhttp3.Call localVarCall = v1ScheduledMailingsGetValidateBeforeCall(null);
        Type localVarReturnType = new TypeToken<ListScheduledMailingsResp>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List scheduled mailings (asynchronously)
     * 
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of scheduled mailings </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsGetAsync(final ApiCallback<ListScheduledMailingsResp> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ScheduledMailingsGetValidateBeforeCall(_callback);
        Type localVarReturnType = new TypeToken<ListScheduledMailingsResp>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ScheduledMailingsMailingIdDelete
     * @param mailingId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Scheduled mailing not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsMailingIdDeleteCall(@javax.annotation.Nonnull String mailingId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/scheduled-mailings/{mailing_id}"
            .replace("{" + "mailing_id" + "}", localVarApiClient.escapeString(mailingId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "DELETE", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ScheduledMailingsMailingIdDeleteValidateBeforeCall(@javax.annotation.Nonnull String mailingId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'mailingId' is set
        if (mailingId == null) {
            throw new ApiException("Missing the required parameter 'mailingId' when calling v1ScheduledMailingsMailingIdDelete(Async)");
        }

        return v1ScheduledMailingsMailingIdDeleteCall(mailingId, _callback);

    }

    /**
     * Delete a scheduled mailing
     * 
     * @param mailingId  (required)
     * @return DeleteScheduledMailingResp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Scheduled mailing not found </td><td>  -  </td></tr>
     </table>
     */
    public DeleteScheduledMailingResp v1ScheduledMailingsMailingIdDelete(@javax.annotation.Nonnull String mailingId) throws ApiException {
        ApiResponse<DeleteScheduledMailingResp> localVarResp = v1ScheduledMailingsMailingIdDeleteWithHttpInfo(mailingId);
        return localVarResp.getData();
    }

    /**
     * Delete a scheduled mailing
     * 
     * @param mailingId  (required)
     * @return ApiResponse&lt;DeleteScheduledMailingResp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Scheduled mailing not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<DeleteScheduledMailingResp> v1ScheduledMailingsMailingIdDeleteWithHttpInfo(@javax.annotation.Nonnull String mailingId) throws ApiException {
        okhttp3.Call localVarCall = v1ScheduledMailingsMailingIdDeleteValidateBeforeCall(mailingId, null);
        Type localVarReturnType = new TypeToken<DeleteScheduledMailingResp>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Delete a scheduled mailing (asynchronously)
     * 
     * @param mailingId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing deleted </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Scheduled mailing not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsMailingIdDeleteAsync(@javax.annotation.Nonnull String mailingId, final ApiCallback<DeleteScheduledMailingResp> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ScheduledMailingsMailingIdDeleteValidateBeforeCall(mailingId, _callback);
        Type localVarReturnType = new TypeToken<DeleteScheduledMailingResp>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ScheduledMailingsMailingIdGet
     * @param mailingId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Scheduled mailing not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsMailingIdGetCall(@javax.annotation.Nonnull String mailingId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/scheduled-mailings/{mailing_id}"
            .replace("{" + "mailing_id" + "}", localVarApiClient.escapeString(mailingId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ScheduledMailingsMailingIdGetValidateBeforeCall(@javax.annotation.Nonnull String mailingId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'mailingId' is set
        if (mailingId == null) {
            throw new ApiException("Missing the required parameter 'mailingId' when calling v1ScheduledMailingsMailingIdGet(Async)");
        }

        return v1ScheduledMailingsMailingIdGetCall(mailingId, _callback);

    }

    /**
     * Get a scheduled mailing by ID
     * 
     * @param mailingId  (required)
     * @return GetScheduledMailingResp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Scheduled mailing not found </td><td>  -  </td></tr>
     </table>
     */
    public GetScheduledMailingResp v1ScheduledMailingsMailingIdGet(@javax.annotation.Nonnull String mailingId) throws ApiException {
        ApiResponse<GetScheduledMailingResp> localVarResp = v1ScheduledMailingsMailingIdGetWithHttpInfo(mailingId);
        return localVarResp.getData();
    }

    /**
     * Get a scheduled mailing by ID
     * 
     * @param mailingId  (required)
     * @return ApiResponse&lt;GetScheduledMailingResp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Scheduled mailing not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<GetScheduledMailingResp> v1ScheduledMailingsMailingIdGetWithHttpInfo(@javax.annotation.Nonnull String mailingId) throws ApiException {
        okhttp3.Call localVarCall = v1ScheduledMailingsMailingIdGetValidateBeforeCall(mailingId, null);
        Type localVarReturnType = new TypeToken<GetScheduledMailingResp>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get a scheduled mailing by ID (asynchronously)
     * 
     * @param mailingId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing details </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Scheduled mailing not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsMailingIdGetAsync(@javax.annotation.Nonnull String mailingId, final ApiCallback<GetScheduledMailingResp> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ScheduledMailingsMailingIdGetValidateBeforeCall(mailingId, _callback);
        Type localVarReturnType = new TypeToken<GetScheduledMailingResp>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ScheduledMailingsMailingIdPut
     * @param mailingId  (required)
     * @param updateScheduledMailingReq  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsMailingIdPutCall(@javax.annotation.Nonnull String mailingId, @javax.annotation.Nonnull UpdateScheduledMailingReq updateScheduledMailingReq, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = updateScheduledMailingReq;

        // create path and map variables
        String localVarPath = "/v1/scheduled-mailings/{mailing_id}"
            .replace("{" + "mailing_id" + "}", localVarApiClient.escapeString(mailingId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ScheduledMailingsMailingIdPutValidateBeforeCall(@javax.annotation.Nonnull String mailingId, @javax.annotation.Nonnull UpdateScheduledMailingReq updateScheduledMailingReq, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'mailingId' is set
        if (mailingId == null) {
            throw new ApiException("Missing the required parameter 'mailingId' when calling v1ScheduledMailingsMailingIdPut(Async)");
        }

        // verify the required parameter 'updateScheduledMailingReq' is set
        if (updateScheduledMailingReq == null) {
            throw new ApiException("Missing the required parameter 'updateScheduledMailingReq' when calling v1ScheduledMailingsMailingIdPut(Async)");
        }

        return v1ScheduledMailingsMailingIdPutCall(mailingId, updateScheduledMailingReq, _callback);

    }

    /**
     * Update a scheduled mailing
     * 
     * @param mailingId  (required)
     * @param updateScheduledMailingReq  (required)
     * @return UpdateScheduledMailingResp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
     </table>
     */
    public UpdateScheduledMailingResp v1ScheduledMailingsMailingIdPut(@javax.annotation.Nonnull String mailingId, @javax.annotation.Nonnull UpdateScheduledMailingReq updateScheduledMailingReq) throws ApiException {
        ApiResponse<UpdateScheduledMailingResp> localVarResp = v1ScheduledMailingsMailingIdPutWithHttpInfo(mailingId, updateScheduledMailingReq);
        return localVarResp.getData();
    }

    /**
     * Update a scheduled mailing
     * 
     * @param mailingId  (required)
     * @param updateScheduledMailingReq  (required)
     * @return ApiResponse&lt;UpdateScheduledMailingResp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<UpdateScheduledMailingResp> v1ScheduledMailingsMailingIdPutWithHttpInfo(@javax.annotation.Nonnull String mailingId, @javax.annotation.Nonnull UpdateScheduledMailingReq updateScheduledMailingReq) throws ApiException {
        okhttp3.Call localVarCall = v1ScheduledMailingsMailingIdPutValidateBeforeCall(mailingId, updateScheduledMailingReq, null);
        Type localVarReturnType = new TypeToken<UpdateScheduledMailingResp>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Update a scheduled mailing (asynchronously)
     * 
     * @param mailingId  (required)
     * @param updateScheduledMailingReq  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing updated </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsMailingIdPutAsync(@javax.annotation.Nonnull String mailingId, @javax.annotation.Nonnull UpdateScheduledMailingReq updateScheduledMailingReq, final ApiCallback<UpdateScheduledMailingResp> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ScheduledMailingsMailingIdPutValidateBeforeCall(mailingId, updateScheduledMailingReq, _callback);
        Type localVarReturnType = new TypeToken<UpdateScheduledMailingResp>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1ScheduledMailingsPost
     * @param createScheduledMailingReq  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient credits or scheduled mailing quota exceeded </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsPostCall(@javax.annotation.Nonnull CreateScheduledMailingReq createScheduledMailingReq, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createScheduledMailingReq;

        // create path and map variables
        String localVarPath = "/v1/scheduled-mailings";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1ScheduledMailingsPostValidateBeforeCall(@javax.annotation.Nonnull CreateScheduledMailingReq createScheduledMailingReq, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createScheduledMailingReq' is set
        if (createScheduledMailingReq == null) {
            throw new ApiException("Missing the required parameter 'createScheduledMailingReq' when calling v1ScheduledMailingsPost(Async)");
        }

        return v1ScheduledMailingsPostCall(createScheduledMailingReq, _callback);

    }

    /**
     * Create a new scheduled mailing
     * 
     * @param createScheduledMailingReq  (required)
     * @return CreateScheduledMailingResp
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient credits or scheduled mailing quota exceeded </td><td>  -  </td></tr>
     </table>
     */
    public CreateScheduledMailingResp v1ScheduledMailingsPost(@javax.annotation.Nonnull CreateScheduledMailingReq createScheduledMailingReq) throws ApiException {
        ApiResponse<CreateScheduledMailingResp> localVarResp = v1ScheduledMailingsPostWithHttpInfo(createScheduledMailingReq);
        return localVarResp.getData();
    }

    /**
     * Create a new scheduled mailing
     * 
     * @param createScheduledMailingReq  (required)
     * @return ApiResponse&lt;CreateScheduledMailingResp&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient credits or scheduled mailing quota exceeded </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CreateScheduledMailingResp> v1ScheduledMailingsPostWithHttpInfo(@javax.annotation.Nonnull CreateScheduledMailingReq createScheduledMailingReq) throws ApiException {
        okhttp3.Call localVarCall = v1ScheduledMailingsPostValidateBeforeCall(createScheduledMailingReq, null);
        Type localVarReturnType = new TypeToken<CreateScheduledMailingResp>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create a new scheduled mailing (asynchronously)
     * 
     * @param createScheduledMailingReq  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Scheduled mailing created successfully </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Insufficient credits or scheduled mailing quota exceeded </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1ScheduledMailingsPostAsync(@javax.annotation.Nonnull CreateScheduledMailingReq createScheduledMailingReq, final ApiCallback<CreateScheduledMailingResp> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1ScheduledMailingsPostValidateBeforeCall(createScheduledMailingReq, _callback);
        Type localVarReturnType = new TypeToken<CreateScheduledMailingResp>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1SendBatchPost
     * @param batchEmail  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Task accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid template/request format. Inactive sender domain </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Quota exhausted or invalid API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1SendBatchPostCall(@javax.annotation.Nonnull BatchEmail batchEmail, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = batchEmail;

        // create path and map variables
        String localVarPath = "/v1/send-batch";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1SendBatchPostValidateBeforeCall(@javax.annotation.Nonnull BatchEmail batchEmail, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'batchEmail' is set
        if (batchEmail == null) {
            throw new ApiException("Missing the required parameter 'batchEmail' when calling v1SendBatchPost(Async)");
        }

        return v1SendBatchPostCall(batchEmail, _callback);

    }

    /**
     * Send templated e-mails to many recipients
     * 
     * @param batchEmail  (required)
     * @return BatchResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Task accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid template/request format. Inactive sender domain </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Quota exhausted or invalid API key </td><td>  -  </td></tr>
     </table>
     */
    public BatchResponse v1SendBatchPost(@javax.annotation.Nonnull BatchEmail batchEmail) throws ApiException {
        ApiResponse<BatchResponse> localVarResp = v1SendBatchPostWithHttpInfo(batchEmail);
        return localVarResp.getData();
    }

    /**
     * Send templated e-mails to many recipients
     * 
     * @param batchEmail  (required)
     * @return ApiResponse&lt;BatchResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Task accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid template/request format. Inactive sender domain </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Quota exhausted or invalid API key </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<BatchResponse> v1SendBatchPostWithHttpInfo(@javax.annotation.Nonnull BatchEmail batchEmail) throws ApiException {
        okhttp3.Call localVarCall = v1SendBatchPostValidateBeforeCall(batchEmail, null);
        Type localVarReturnType = new TypeToken<BatchResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Send templated e-mails to many recipients (asynchronously)
     * 
     * @param batchEmail  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Task accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid template/request format. Inactive sender domain </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Quota exhausted or invalid API key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1SendBatchPostAsync(@javax.annotation.Nonnull BatchEmail batchEmail, final ApiCallback<BatchResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1SendBatchPostValidateBeforeCall(batchEmail, _callback);
        Type localVarReturnType = new TypeToken<BatchResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1TasksPost
     * @param createTaskRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Task created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Quota exhausted / invalid key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TasksPostCall(@javax.annotation.Nonnull CreateTaskRequest createTaskRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createTaskRequest;

        // create path and map variables
        String localVarPath = "/v1/tasks";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1TasksPostValidateBeforeCall(@javax.annotation.Nonnull CreateTaskRequest createTaskRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createTaskRequest' is set
        if (createTaskRequest == null) {
            throw new ApiException("Missing the required parameter 'createTaskRequest' when calling v1TasksPost(Async)");
        }

        return v1TasksPostCall(createTaskRequest, _callback);

    }

    /**
     * Create verification task
     * 
     * @param createTaskRequest  (required)
     * @return TaskResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Task created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Quota exhausted / invalid key </td><td>  -  </td></tr>
     </table>
     */
    public TaskResponse v1TasksPost(@javax.annotation.Nonnull CreateTaskRequest createTaskRequest) throws ApiException {
        ApiResponse<TaskResponse> localVarResp = v1TasksPostWithHttpInfo(createTaskRequest);
        return localVarResp.getData();
    }

    /**
     * Create verification task
     * 
     * @param createTaskRequest  (required)
     * @return ApiResponse&lt;TaskResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Task created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Quota exhausted / invalid key </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TaskResponse> v1TasksPostWithHttpInfo(@javax.annotation.Nonnull CreateTaskRequest createTaskRequest) throws ApiException {
        okhttp3.Call localVarCall = v1TasksPostValidateBeforeCall(createTaskRequest, null);
        Type localVarReturnType = new TypeToken<TaskResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Create verification task (asynchronously)
     * 
     * @param createTaskRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Task created </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad request </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Quota exhausted / invalid key </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TasksPostAsync(@javax.annotation.Nonnull CreateTaskRequest createTaskRequest, final ApiCallback<TaskResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1TasksPostValidateBeforeCall(createTaskRequest, _callback);
        Type localVarReturnType = new TypeToken<TaskResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1TasksResultsTaskIdGet
     * @param taskId  (required)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 100)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TasksResultsTaskIdGetCall(@javax.annotation.Nonnull String taskId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/tasks-results/{task_id}"
            .replace("{" + "task_id" + "}", localVarApiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        if (page != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("page", page));
        }

        if (perPage != null) {
            localVarQueryParams.addAll(localVarApiClient.parameterToPair("per_page", perPage));
        }

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1TasksResultsTaskIdGetValidateBeforeCall(@javax.annotation.Nonnull String taskId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException("Missing the required parameter 'taskId' when calling v1TasksResultsTaskIdGet(Async)");
        }

        return v1TasksResultsTaskIdGetCall(taskId, page, perPage, _callback);

    }

    /**
     * Paginated verification results
     * 
     * @param taskId  (required)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 100)
     * @return PaginatedResults
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public PaginatedResults v1TasksResultsTaskIdGet(@javax.annotation.Nonnull String taskId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage) throws ApiException {
        ApiResponse<PaginatedResults> localVarResp = v1TasksResultsTaskIdGetWithHttpInfo(taskId, page, perPage);
        return localVarResp.getData();
    }

    /**
     * Paginated verification results
     * 
     * @param taskId  (required)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 100)
     * @return ApiResponse&lt;PaginatedResults&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<PaginatedResults> v1TasksResultsTaskIdGetWithHttpInfo(@javax.annotation.Nonnull String taskId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage) throws ApiException {
        okhttp3.Call localVarCall = v1TasksResultsTaskIdGetValidateBeforeCall(taskId, page, perPage, null);
        Type localVarReturnType = new TypeToken<PaginatedResults>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Paginated verification results (asynchronously)
     * 
     * @param taskId  (required)
     * @param page  (optional, default to 1)
     * @param perPage  (optional, default to 100)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TasksResultsTaskIdGetAsync(@javax.annotation.Nonnull String taskId, @javax.annotation.Nullable Integer page, @javax.annotation.Nullable Integer perPage, final ApiCallback<PaginatedResults> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1TasksResultsTaskIdGetValidateBeforeCall(taskId, page, perPage, _callback);
        Type localVarReturnType = new TypeToken<PaginatedResults>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for v1TasksTaskIdGet
     * @param taskId  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Task not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TasksTaskIdGetCall(@javax.annotation.Nonnull String taskId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/v1/tasks/{task_id}"
            .replace("{" + "task_id" + "}", localVarApiClient.escapeString(taskId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "ApiKeyAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call v1TasksTaskIdGetValidateBeforeCall(@javax.annotation.Nonnull String taskId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'taskId' is set
        if (taskId == null) {
            throw new ApiException("Missing the required parameter 'taskId' when calling v1TasksTaskIdGet(Async)");
        }

        return v1TasksTaskIdGetCall(taskId, _callback);

    }

    /**
     * Get verification task status
     * 
     * @param taskId  (required)
     * @return TaskStatusResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Task not found </td><td>  -  </td></tr>
     </table>
     */
    public TaskStatusResponse v1TasksTaskIdGet(@javax.annotation.Nonnull String taskId) throws ApiException {
        ApiResponse<TaskStatusResponse> localVarResp = v1TasksTaskIdGetWithHttpInfo(taskId);
        return localVarResp.getData();
    }

    /**
     * Get verification task status
     * 
     * @param taskId  (required)
     * @return ApiResponse&lt;TaskStatusResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Task not found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<TaskStatusResponse> v1TasksTaskIdGetWithHttpInfo(@javax.annotation.Nonnull String taskId) throws ApiException {
        okhttp3.Call localVarCall = v1TasksTaskIdGetValidateBeforeCall(taskId, null);
        Type localVarReturnType = new TypeToken<TaskStatusResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get verification task status (asynchronously)
     * 
     * @param taskId  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Task not found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call v1TasksTaskIdGetAsync(@javax.annotation.Nonnull String taskId, final ApiCallback<TaskStatusResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = v1TasksTaskIdGetValidateBeforeCall(taskId, _callback);
        Type localVarReturnType = new TypeToken<TaskStatusResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
