/*
 * ZBounce Email-Checker API
 * Batch and real-time email verification.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Date;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for APIKeyInfo
 */
public class APIKeyInfoTest {
    private final APIKeyInfo model = new APIKeyInfo();

    /**
     * Model tests for APIKeyInfo
     */
    @Test
    public void testAPIKeyInfo() {
        // TODO: test APIKeyInfo
    }

    /**
     * Test the property 'apiKey'
     */
    @Test
    public void apiKeyTest() {
        // TODO: test apiKey
    }

    /**
     * Test the property 'keyType'
     */
    @Test
    public void keyTypeTest() {
        // TODO: test keyType
    }

    /**
     * Test the property 'remainingChecks'
     */
    @Test
    public void remainingChecksTest() {
        // TODO: test remainingChecks
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    public void expiresAtTest() {
        // TODO: test expiresAt
    }

}
