/*
 * ZBounce Email Engine Platform
 * ZBounce Email Engine Platform API Reference
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Attachment
 */
public class AttachmentTest {
    private final Attachment model = new Attachment();

    /**
     * Model tests for Attachment
     */
    @Test
    public void testAttachment() {
        // TODO: test Attachment
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'mime'
     */
    @Test
    public void mimeTest() {
        // TODO: test mime
    }

    /**
     * Test the property 'b64'
     */
    @Test
    public void b64Test() {
        // TODO: test b64
    }

}
