/*
 * ZBounce Email Engine Platform
 * ZBounce Email Engine Platform API Reference
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Recipient;
import org.openapitools.client.model.Template;
import org.openapitools.client.model.WebhookConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BatchEmail
 */
public class BatchEmailTest {
    private final BatchEmail model = new BatchEmail();

    /**
     * Model tests for BatchEmail
     */
    @Test
    public void testBatchEmail() {
        // TODO: test BatchEmail
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    public void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'validate'
     */
    @Test
    public void validateTest() {
        // TODO: test validate
    }

    /**
     * Test the property 'skipDisposable'
     */
    @Test
    public void skipDisposableTest() {
        // TODO: test skipDisposable
    }

    /**
     * Test the property 'skipRisky'
     */
    @Test
    public void skipRiskyTest() {
        // TODO: test skipRisky
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'hook'
     */
    @Test
    public void hookTest() {
        // TODO: test hook
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
