/*
 * ZBounce Email-Checker API
 * Batch and real-time email verification.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateKeyRequest
 */
public class CreateKeyRequestTest {
    private final CreateKeyRequest model = new CreateKeyRequest();

    /**
     * Model tests for CreateKeyRequest
     */
    @Test
    public void testCreateKeyRequest() {
        // TODO: test CreateKeyRequest
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'initialChecks'
     */
    @Test
    public void initialChecksTest() {
        // TODO: test initialChecks
    }

    /**
     * Test the property 'validityDays'
     */
    @Test
    public void validityDaysTest() {
        // TODO: test validityDays
    }

}
