/*
 * ZBounce Email Engine Platform
 * ZBounce Email Engine Platform API Reference
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Template;
import org.openapitools.client.model.WebhookConfig;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateScheduledMailingReq
 */
public class CreateScheduledMailingReqTest {
    private final CreateScheduledMailingReq model = new CreateScheduledMailingReq();

    /**
     * Model tests for CreateScheduledMailingReq
     */
    @Test
    public void testCreateScheduledMailingReq() {
        // TODO: test CreateScheduledMailingReq
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    public void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'scheduledTime'
     */
    @Test
    public void scheduledTimeTest() {
        // TODO: test scheduledTime
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'recurring'
     */
    @Test
    public void recurringTest() {
        // TODO: test recurring
    }

    /**
     * Test the property 'recurrenceInterval'
     */
    @Test
    public void recurrenceIntervalTest() {
        // TODO: test recurrenceInterval
    }

    /**
     * Test the property 'hook'
     */
    @Test
    public void hookTest() {
        // TODO: test hook
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
