/*
 * ZBounce Email Engine Platform
 * ZBounce Email Engine Platform API Reference
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ScheduledMailing;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateScheduledMailingResp
 */
public class CreateScheduledMailingRespTest {
    private final CreateScheduledMailingResp model = new CreateScheduledMailingResp();

    /**
     * Model tests for CreateScheduledMailingResp
     */
    @Test
    public void testCreateScheduledMailingResp() {
        // TODO: test CreateScheduledMailingResp
    }

    /**
     * Test the property 'mailing'
     */
    @Test
    public void mailingTest() {
        // TODO: test mailing
    }

}
