/*
 * ZBounce Email-Checker API
 * Batch and real-time email verification.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EmailReport
 */
public class EmailReportTest {
    private final EmailReport model = new EmailReport();

    /**
     * Model tests for EmailReport
     */
    @Test
    public void testEmailReport() {
        // TODO: test EmailReport
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

    /**
     * Test the property 'disposable'
     */
    @Test
    public void disposableTest() {
        // TODO: test disposable
    }

    /**
     * Test the property 'exists'
     */
    @Test
    public void existsTest() {
        // TODO: test exists
    }

    /**
     * Test the property 'permanentError'
     */
    @Test
    public void permanentErrorTest() {
        // TODO: test permanentError
    }

    /**
     * Test the property 'errorCategory'
     */
    @Test
    public void errorCategoryTest() {
        // TODO: test errorCategory
    }

    /**
     * Test the property 'ttl'
     */
    @Test
    public void ttlTest() {
        // TODO: test ttl
    }

    /**
     * Test the property 'acceptAll'
     */
    @Test
    public void acceptAllTest() {
        // TODO: test acceptAll
    }

}
