/*
 * ZBounce Email-Checker API
 * Batch and real-time email verification.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FastVerifyRequest
 */
public class FastVerifyRequestTest {
    private final FastVerifyRequest model = new FastVerifyRequest();

    /**
     * Model tests for FastVerifyRequest
     */
    @Test
    public void testFastVerifyRequest() {
        // TODO: test FastVerifyRequest
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

}
