/*
 * ZBounce Email Engine Platform
 * ZBounce Email Engine Platform API Reference
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendEmailReq
 */
public class SendEmailReqTest {
    private final SendEmailReq model = new SendEmailReq();

    /**
     * Model tests for SendEmailReq
     */
    @Test
    public void testSendEmailReq() {
        // TODO: test SendEmailReq
    }

    /**
     * Test the property 'from'
     */
    @Test
    public void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    public void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'html'
     */
    @Test
    public void htmlTest() {
        // TODO: test html
    }

    /**
     * Test the property 'validate'
     */
    @Test
    public void validateTest() {
        // TODO: test validate
    }

    /**
     * Test the property 'skipDisposable'
     */
    @Test
    public void skipDisposableTest() {
        // TODO: test skipDisposable
    }

    /**
     * Test the property 'skipAcceptAll'
     */
    @Test
    public void skipAcceptAllTest() {
        // TODO: test skipAcceptAll
    }

}
