/*
 * ZBounce Email-Checker API
 * Batch and real-time email verification.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TaskResponse
 */
public class TaskResponseTest {
    private final TaskResponse model = new TaskResponse();

    /**
     * Model tests for TaskResponse
     */
    @Test
    public void testTaskResponse() {
        // TODO: test TaskResponse
    }

    /**
     * Test the property 'taskId'
     */
    @Test
    public void taskIdTest() {
        // TODO: test taskId
    }

    /**
     * Test the property 'accepted'
     */
    @Test
    public void acceptedTest() {
        // TODO: test accepted
    }

    /**
     * Test the property 'skipped'
     */
    @Test
    public void skippedTest() {
        // TODO: test skipped
    }

}
