/*
 * ZBounce Email-Checker API
 * Batch and real-time email verification.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateKeyRequest
 */
public class UpdateKeyRequestTest {
    private final UpdateKeyRequest model = new UpdateKeyRequest();

    /**
     * Model tests for UpdateKeyRequest
     */
    @Test
    public void testUpdateKeyRequest() {
        // TODO: test UpdateKeyRequest
    }

    /**
     * Test the property 'addChecks'
     */
    @Test
    public void addChecksTest() {
        // TODO: test addChecks
    }

    /**
     * Test the property 'extendDays'
     */
    @Test
    public void extendDaysTest() {
        // TODO: test extendDays
    }

}
