/*
 * ZBounce Email Engine Platform
 * ZBounce Email Engine Platform API Reference
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V1DomainsDomainPatch200Response
 */
public class V1DomainsDomainPatch200ResponseTest {
    private final V1DomainsDomainPatch200Response model = new V1DomainsDomainPatch200Response();

    /**
     * Model tests for V1DomainsDomainPatch200Response
     */
    @Test
    public void testV1DomainsDomainPatch200Response() {
        // TODO: test V1DomainsDomainPatch200Response
    }

    /**
     * Test the property 'verified'
     */
    @Test
    public void verifiedTest() {
        // TODO: test verified
    }

}
