/*
 * ZBounce Email-Checker API
 * Batch and real-time email verification.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.openapitools.client.model.BasicAuth;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhookConfig
 */
public class WebhookConfigTest {
    private final WebhookConfig model = new WebhookConfig();

    /**
     * Model tests for WebhookConfig
     */
    @Test
    public void testWebhookConfig() {
        // TODO: test WebhookConfig
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'secret'
     */
    @Test
    public void secretTest() {
        // TODO: test secret
    }

    /**
     * Test the property 'mode'
     */
    @Test
    public void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'maxRetries'
     */
    @Test
    public void maxRetriesTest() {
        // TODO: test maxRetries
    }

    /**
     * Test the property 'timeoutMs'
     */
    @Test
    public void timeoutMsTest() {
        // TODO: test timeoutMs
    }

    /**
     * Test the property 'dlqUrl'
     */
    @Test
    public void dlqUrlTest() {
        // TODO: test dlqUrl
    }

    /**
     * Test the property 'basicAuth'
     */
    @Test
    public void basicAuthTest() {
        // TODO: test basicAuth
    }

}
