/*
 * ZBounce Email Engine Platform
 * ZBounce Email Engine Platform API Reference
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Template;
import org.openapitools.client.model.WebhookConfig;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Request schema for creating a new scheduled mailing. Contains the email template, recipient list, client-provided scheduled time (ISO8601), timezone, recurring flag, recurrence interval (if applicable), number of credits to reserve, and an optional webhook configuration.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-27T09:35:58.468477+03:00[Europe/Minsk]", comments = "Generator version: 7.13.0")
public class CreateScheduledMailingReq implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_TEMPLATE = "template";
  @SerializedName(SERIALIZED_NAME_TEMPLATE)
  @javax.annotation.Nonnull
  private Template template;

  public static final String SERIALIZED_NAME_RECIPIENTS = "recipients";
  @SerializedName(SERIALIZED_NAME_RECIPIENTS)
  @javax.annotation.Nonnull
  private List<String> recipients = new ArrayList<>();

  public static final String SERIALIZED_NAME_SCHEDULED_TIME = "scheduled_time";
  @SerializedName(SERIALIZED_NAME_SCHEDULED_TIME)
  @javax.annotation.Nonnull
  private String scheduledTime;

  public static final String SERIALIZED_NAME_TIMEZONE = "timezone";
  @SerializedName(SERIALIZED_NAME_TIMEZONE)
  @javax.annotation.Nonnull
  private String timezone;

  public static final String SERIALIZED_NAME_RECURRING = "recurring";
  @SerializedName(SERIALIZED_NAME_RECURRING)
  @javax.annotation.Nonnull
  private Boolean recurring;

  public static final String SERIALIZED_NAME_RECURRENCE_INTERVAL = "recurrence_interval";
  @SerializedName(SERIALIZED_NAME_RECURRENCE_INTERVAL)
  @javax.annotation.Nullable
  private String recurrenceInterval;

  public static final String SERIALIZED_NAME_HOOK = "hook";
  @SerializedName(SERIALIZED_NAME_HOOK)
  @javax.annotation.Nullable
  private WebhookConfig hook;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public CreateScheduledMailingReq() {
  }

  public CreateScheduledMailingReq template(@javax.annotation.Nonnull Template template) {
    this.template = template;
    return this;
  }

  /**
   * Get template
   * @return template
   */
  @javax.annotation.Nonnull
  public Template getTemplate() {
    return template;
  }

  public void setTemplate(@javax.annotation.Nonnull Template template) {
    this.template = template;
  }


  public CreateScheduledMailingReq recipients(@javax.annotation.Nonnull List<String> recipients) {
    this.recipients = recipients;
    return this;
  }

  public CreateScheduledMailingReq addRecipientsItem(String recipientsItem) {
    if (this.recipients == null) {
      this.recipients = new ArrayList<>();
    }
    this.recipients.add(recipientsItem);
    return this;
  }

  /**
   * List of recipient email addresses.
   * @return recipients
   */
  @javax.annotation.Nonnull
  public List<String> getRecipients() {
    return recipients;
  }

  public void setRecipients(@javax.annotation.Nonnull List<String> recipients) {
    this.recipients = recipients;
  }


  public CreateScheduledMailingReq scheduledTime(@javax.annotation.Nonnull String scheduledTime) {
    this.scheduledTime = scheduledTime;
    return this;
  }

  /**
   * Client-provided scheduled start time in ISO8601 format (with timezone).
   * @return scheduledTime
   */
  @javax.annotation.Nonnull
  public String getScheduledTime() {
    return scheduledTime;
  }

  public void setScheduledTime(@javax.annotation.Nonnull String scheduledTime) {
    this.scheduledTime = scheduledTime;
  }


  public CreateScheduledMailingReq timezone(@javax.annotation.Nonnull String timezone) {
    this.timezone = timezone;
    return this;
  }

  /**
   * The client&#39;s timezone (e.g., &#39;America/New_York&#39;, &#39;America/Toronto&#39;, &#39;Europe/Paris&#39;).
   * @return timezone
   */
  @javax.annotation.Nonnull
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(@javax.annotation.Nonnull String timezone) {
    this.timezone = timezone;
  }


  public CreateScheduledMailingReq recurring(@javax.annotation.Nonnull Boolean recurring) {
    this.recurring = recurring;
    return this;
  }

  /**
   * Indicates whether the mailing is recurring.
   * @return recurring
   */
  @javax.annotation.Nonnull
  public Boolean getRecurring() {
    return recurring;
  }

  public void setRecurring(@javax.annotation.Nonnull Boolean recurring) {
    this.recurring = recurring;
  }


  public CreateScheduledMailingReq recurrenceInterval(@javax.annotation.Nullable String recurrenceInterval) {
    this.recurrenceInterval = recurrenceInterval;
    return this;
  }

  /**
   * Interval for recurring mailings (e.g., &#39;1 week&#39;).
   * @return recurrenceInterval
   */
  @javax.annotation.Nullable
  public String getRecurrenceInterval() {
    return recurrenceInterval;
  }

  public void setRecurrenceInterval(@javax.annotation.Nullable String recurrenceInterval) {
    this.recurrenceInterval = recurrenceInterval;
  }


  public CreateScheduledMailingReq hook(@javax.annotation.Nullable WebhookConfig hook) {
    this.hook = hook;
    return this;
  }

  /**
   * Get hook
   * @return hook
   */
  @javax.annotation.Nullable
  public WebhookConfig getHook() {
    return hook;
  }

  public void setHook(@javax.annotation.Nullable WebhookConfig hook) {
    this.hook = hook;
  }


  public CreateScheduledMailingReq tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public CreateScheduledMailingReq addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Optional tags associated with this scheduled mailing.
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateScheduledMailingReq createScheduledMailingReq = (CreateScheduledMailingReq) o;
    return Objects.equals(this.template, createScheduledMailingReq.template) &&
        Objects.equals(this.recipients, createScheduledMailingReq.recipients) &&
        Objects.equals(this.scheduledTime, createScheduledMailingReq.scheduledTime) &&
        Objects.equals(this.timezone, createScheduledMailingReq.timezone) &&
        Objects.equals(this.recurring, createScheduledMailingReq.recurring) &&
        Objects.equals(this.recurrenceInterval, createScheduledMailingReq.recurrenceInterval) &&
        Objects.equals(this.hook, createScheduledMailingReq.hook) &&
        Objects.equals(this.tags, createScheduledMailingReq.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(template, recipients, scheduledTime, timezone, recurring, recurrenceInterval, hook, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateScheduledMailingReq {\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    scheduledTime: ").append(toIndentedString(scheduledTime)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    recurring: ").append(toIndentedString(recurring)).append("\n");
    sb.append("    recurrenceInterval: ").append(toIndentedString(recurrenceInterval)).append("\n");
    sb.append("    hook: ").append(toIndentedString(hook)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("template");
    openapiFields.add("recipients");
    openapiFields.add("scheduled_time");
    openapiFields.add("timezone");
    openapiFields.add("recurring");
    openapiFields.add("recurrence_interval");
    openapiFields.add("hook");
    openapiFields.add("tags");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("template");
    openapiRequiredFields.add("recipients");
    openapiRequiredFields.add("scheduled_time");
    openapiRequiredFields.add("timezone");
    openapiRequiredFields.add("recurring");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CreateScheduledMailingReq
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CreateScheduledMailingReq.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CreateScheduledMailingReq is not found in the empty JSON string", CreateScheduledMailingReq.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CreateScheduledMailingReq.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CreateScheduledMailingReq` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CreateScheduledMailingReq.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `template`
      Template.validateJsonElement(jsonObj.get("template"));
      // ensure the required json array is present
      if (jsonObj.get("recipients") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("recipients").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `recipients` to be an array in the JSON string but got `%s`", jsonObj.get("recipients").toString()));
      }
      if (!jsonObj.get("scheduled_time").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `scheduled_time` to be a primitive type in the JSON string but got `%s`", jsonObj.get("scheduled_time").toString()));
      }
      if (!jsonObj.get("timezone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `timezone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("timezone").toString()));
      }
      if ((jsonObj.get("recurrence_interval") != null && !jsonObj.get("recurrence_interval").isJsonNull()) && !jsonObj.get("recurrence_interval").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `recurrence_interval` to be a primitive type in the JSON string but got `%s`", jsonObj.get("recurrence_interval").toString()));
      }
      // validate the optional field `hook`
      if (jsonObj.get("hook") != null && !jsonObj.get("hook").isJsonNull()) {
        WebhookConfig.validateJsonElement(jsonObj.get("hook"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CreateScheduledMailingReq.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CreateScheduledMailingReq' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CreateScheduledMailingReq> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CreateScheduledMailingReq.class));

       return (TypeAdapter<T>) new TypeAdapter<CreateScheduledMailingReq>() {
           @Override
           public void write(JsonWriter out, CreateScheduledMailingReq value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CreateScheduledMailingReq read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CreateScheduledMailingReq given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CreateScheduledMailingReq
   * @throws IOException if the JSON string is invalid with respect to CreateScheduledMailingReq
   */
  public static CreateScheduledMailingReq fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CreateScheduledMailingReq.class);
  }

  /**
   * Convert an instance of CreateScheduledMailingReq to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

