/*
 * ZBounce Email Engine Platform
 * ZBounce Email Engine Platform API Reference
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.ScheduledMailing;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Response schema for listing scheduled mailings. Returns an array of scheduled mailing objects.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-27T09:35:58.468477+03:00[Europe/Minsk]", comments = "Generator version: 7.13.0")
public class ListScheduledMailingsResp implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_MAILINGS = "mailings";
  @SerializedName(SERIALIZED_NAME_MAILINGS)
  @javax.annotation.Nullable
  private List<ScheduledMailing> mailings = new ArrayList<>();

  public ListScheduledMailingsResp() {
  }

  public ListScheduledMailingsResp mailings(@javax.annotation.Nullable List<ScheduledMailing> mailings) {
    this.mailings = mailings;
    return this;
  }

  public ListScheduledMailingsResp addMailingsItem(ScheduledMailing mailingsItem) {
    if (this.mailings == null) {
      this.mailings = new ArrayList<>();
    }
    this.mailings.add(mailingsItem);
    return this;
  }

  /**
   * List of scheduled mailings associated with the authenticated API key.
   * @return mailings
   */
  @javax.annotation.Nullable
  public List<ScheduledMailing> getMailings() {
    return mailings;
  }

  public void setMailings(@javax.annotation.Nullable List<ScheduledMailing> mailings) {
    this.mailings = mailings;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListScheduledMailingsResp listScheduledMailingsResp = (ListScheduledMailingsResp) o;
    return Objects.equals(this.mailings, listScheduledMailingsResp.mailings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mailings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListScheduledMailingsResp {\n");
    sb.append("    mailings: ").append(toIndentedString(mailings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("mailings");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ListScheduledMailingsResp
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ListScheduledMailingsResp.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ListScheduledMailingsResp is not found in the empty JSON string", ListScheduledMailingsResp.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ListScheduledMailingsResp.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ListScheduledMailingsResp` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("mailings") != null && !jsonObj.get("mailings").isJsonNull()) {
        JsonArray jsonArraymailings = jsonObj.getAsJsonArray("mailings");
        if (jsonArraymailings != null) {
          // ensure the json data is an array
          if (!jsonObj.get("mailings").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `mailings` to be an array in the JSON string but got `%s`", jsonObj.get("mailings").toString()));
          }

          // validate the optional field `mailings` (array)
          for (int i = 0; i < jsonArraymailings.size(); i++) {
            ScheduledMailing.validateJsonElement(jsonArraymailings.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ListScheduledMailingsResp.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ListScheduledMailingsResp' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ListScheduledMailingsResp> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ListScheduledMailingsResp.class));

       return (TypeAdapter<T>) new TypeAdapter<ListScheduledMailingsResp>() {
           @Override
           public void write(JsonWriter out, ListScheduledMailingsResp value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ListScheduledMailingsResp read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ListScheduledMailingsResp given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ListScheduledMailingsResp
   * @throws IOException if the JSON string is invalid with respect to ListScheduledMailingsResp
   */
  public static ListScheduledMailingsResp fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ListScheduledMailingsResp.class);
  }

  /**
   * Convert an instance of ListScheduledMailingsResp to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

