/*
 * ZBounce Email-Checker API
 * Batch and real-time email verification.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.io.Serializable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UpdateKeyRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-13T15:19:56.609676+03:00[Europe/Minsk]", comments = "Generator version: 7.13.0")
public class UpdateKeyRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ADD_CHECKS = "add_checks";
  @SerializedName(SERIALIZED_NAME_ADD_CHECKS)
  @javax.annotation.Nullable
  private Integer addChecks;

  public static final String SERIALIZED_NAME_EXTEND_DAYS = "extend_days";
  @SerializedName(SERIALIZED_NAME_EXTEND_DAYS)
  @javax.annotation.Nullable
  private Integer extendDays;

  public UpdateKeyRequest() {
  }

  public UpdateKeyRequest addChecks(@javax.annotation.Nullable Integer addChecks) {
    this.addChecks = addChecks;
    return this;
  }

  /**
   * Get addChecks
   * minimum: 1
   * @return addChecks
   */
  @javax.annotation.Nullable
  public Integer getAddChecks() {
    return addChecks;
  }

  public void setAddChecks(@javax.annotation.Nullable Integer addChecks) {
    this.addChecks = addChecks;
  }


  public UpdateKeyRequest extendDays(@javax.annotation.Nullable Integer extendDays) {
    this.extendDays = extendDays;
    return this;
  }

  /**
   * Get extendDays
   * minimum: 1
   * @return extendDays
   */
  @javax.annotation.Nullable
  public Integer getExtendDays() {
    return extendDays;
  }

  public void setExtendDays(@javax.annotation.Nullable Integer extendDays) {
    this.extendDays = extendDays;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateKeyRequest updateKeyRequest = (UpdateKeyRequest) o;
    return Objects.equals(this.addChecks, updateKeyRequest.addChecks) &&
        Objects.equals(this.extendDays, updateKeyRequest.extendDays);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addChecks, extendDays);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateKeyRequest {\n");
    sb.append("    addChecks: ").append(toIndentedString(addChecks)).append("\n");
    sb.append("    extendDays: ").append(toIndentedString(extendDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("add_checks");
    openapiFields.add("extend_days");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateKeyRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateKeyRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UpdateKeyRequest is not found in the empty JSON string", UpdateKeyRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateKeyRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UpdateKeyRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateKeyRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateKeyRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateKeyRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateKeyRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateKeyRequest>() {
           @Override
           public void write(JsonWriter out, UpdateKeyRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateKeyRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateKeyRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateKeyRequest
   * @throws IOException if the JSON string is invalid with respect to UpdateKeyRequest
   */
  public static UpdateKeyRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateKeyRequest.class);
  }

  /**
   * Convert an instance of UpdateKeyRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

