/*
 * ZBounce Email-Checker API
 * Batch and real-time email verification.
 *
 * The version of the OpenAPI document: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.CreateTaskRequest;
import org.openapitools.client.model.EmailReport;
import org.openapitools.client.model.FastVerifyRequest;
import org.openapitools.client.model.PaginatedResults;
import org.openapitools.client.model.TaskResponse;
import org.openapitools.client.model.TaskStatusResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PublicApi
 */
@Disabled
public class PublicApiTest {

    private final PublicApi api = new PublicApi();

    /**
     * Fast single-email verification
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1FastVerifyPostTest() throws ApiException {
        FastVerifyRequest fastVerifyRequest = null;
        EmailReport response = api.v1FastVerifyPost(fastVerifyRequest);
        // TODO: test validations
    }

    /**
     * Create batch verification task
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TasksPostTest() throws ApiException {
        CreateTaskRequest createTaskRequest = null;
        TaskResponse response = api.v1TasksPost(createTaskRequest);
        // TODO: test validations
    }

    /**
     * Paginated task results
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TasksResultsTaskIdGetTest() throws ApiException {
        String taskId = null;
        Integer page = null;
        Integer perPage = null;
        PaginatedResults response = api.v1TasksResultsTaskIdGet(taskId, page, perPage);
        // TODO: test validations
    }

    /**
     * Get task status
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v1TasksTaskIdGetTest() throws ApiException {
        String taskId = null;
        TaskStatusResponse response = api.v1TasksTaskIdGet(taskId);
        // TODO: test validations
    }

}
